version: '3.9'

networks:
  hashicorp:
    driver: bridge

volumes:
  vault: {}

services:
  vault:
    image: "vault:1.7.1"
    volumes:
    - vault:/vault
    ports:
    - 1234:1234
    cap_add:
    - IPC_LOCK
    environment:
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:1234"
      VAULT_DEV_ROOT_TOKEN_ID: "r00tme"
    networks:
    - hashicorp